### PR TITLE
solarcycle.py revision

### PR DESCRIPTION
**Pull request by Joseph0M**

### CODE REVIEW

**Comment by Joseph0M** [comment]
filed in error.

**Comment by stevenbennett** [comment]
Well this looks cool

**Comment by Joseph0M** [comment]
Accidentally clicked the wrong button. I was just preparing it.

**Comment by stevenbennett** [comment]
All good 🙂

**Comment by Joseph0M** [comment]
Stay tuned, il post the proper, updated version soon.

**Pull request closed without merging**
